### ISSUE TITLE
There is a discrepancy between count_tokens_for_message() and API

### ISSUE THREAD

**Issue by WongSaang** [pamelafox/llm-messages-token-helper#1]
Hello, 

First of all, thank you for your excellent work.

when I compare the results of `count_tokens_for_message()` with token counting by the OpenAI API, the count from `count_tokens_for_message()` is always slightly higher than the count returned by the API.

However, when I comment out the following code, their results are the same. It seems like OpenAI does not count tokens for this part.

```python
...
for item in value:
    # num_tokens += len(encoding.encode(item["type"]))
    if item["type"] == "text":
        num_tokens += len(encoding.encode(item["text"]))
    elif item["type"] == "image_url":
        num_tokens += count_tokens_for_image(item["image_url"]["url"], item["image_url"]["detail"])
...
```

**Comment by pamelafox** [comment]
Thanks for the report! I'm digging into this now and adding verification checks with actual OpenAI reported usage.

**Comment by pamelafox** [comment]
I've merged the fix and tests, will publish new version tomorrow.

**Comment by pamelafox** [comment]
FYI, I've published, and also renamed the package to fit its current focus better:
https://pypi.org/project/openai-messages-token-helper/

**Comment by WongSaang** [comment]
Great!
